# Generated by Django 3.0.5 on 2020-04-19 18:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('salary', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
                ('grammature_per_package', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('netto_price_per_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netto_price_per_unit', models.DecimalField(decimal_places=6, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brutto_price_per_package', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('brutto_price_per_unit', models.DecimalField(decimal_places=6, max_digits=10)),
                ('amount_in_storage', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammature', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BistroManagementToolApp.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('monthly_potential', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('share_in_sales', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('brutto_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('netto_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=6, default='0.00', max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('unit_margin', models.DecimalField(decimal_places=6, default='0.00', max_digits=10)),
                ('product_margin', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default='0.00', max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=6, default='0.00', max_digits=10)),
                ('vat_paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('vat_due', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkScheadule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], default='CARD', max_length=4)),
                ('netto_transaction_value', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('netto_transaction_value_5_VAT', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('netto_transaction_value_8_VAT', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('netto_transaction_value_23_VAT', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('brutto_transaction_value', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='BistroManagementToolApp.ApplicationUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_transaction', to='BistroManagementToolApp.Product')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='BistroManagementToolApp.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='BistroManagementToolApp.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='BistroManagementToolApp.ProductGroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='BistroManagementToolApp.IngredientsInProduct', to='BistroManagementToolApp.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='BistroManagementToolApp.ProductType'),
        ),
        migrations.CreateModel(
            name='IngredientSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='BistroManagementToolApp.IngredientCategory')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientsinproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BistroManagementToolApp.Product'),
        ),
        migrations.CreateModel(
            name='IngredientAisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='BistroManagementToolApp.IngredientCategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='BistroManagementToolApp.IngredientSubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='BistroManagementToolApp.IngredientAisle'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='BistroManagementToolApp.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='BistroManagementToolApp.IngredientSubcategory'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='work_scheadule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BistroManagementToolApp.WorkScheadule'),
        ),
    ]
