# Generated by Django 3.0.5 on 2020-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BistroManagementToolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='products_in_transaction',
            field=models.ManyToManyField(through='BistroManagementToolApp.ProductsInTransaction', to='BistroManagementToolApp.Product'),
        ),
    ]
