# Generated by Django 3.0.5 on 2020-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BistroManagementToolApp', '0004_auto_20200524_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products_in_transaction',
            field=models.ManyToManyField(blank=True, null=True, through='BistroManagementToolApp.ProductsInTransaction', to='BistroManagementToolApp.Product'),
        ),
    ]
